const express = require('express');
const path = require('path');
const app = express();

// Use Render's assigned dynamic port or default to 3000 locally
const PORT = process.env.PORT || 3000;

// Serve all static build files generated by Vite
app.use(express.static(path.join(__dirname, 'dist')));

// Fallback to routing all entry views directly through your single page index.html
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`Server running smoothly on port ${PORT}`);
});
